# Generated by Django 4.2.5 on 2023-09-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=25)),
                ('size', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
